apiVersion: v1
kind: Namespace
metadata:
  name: devops-app
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: devops-app
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
